version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - cypress
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - cypress

  cypress:
    image: cypress/included:12.17.0
    depends_on:
      - frontend
      - backend
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:5173

    command: cypress run --config-file cypress.config.ts
    networks:
      - cypress

networks:
  cypress:
    driver: bridge
